"""
Celery task for initiating patient feedback voice calls.

Integrates:
- Twilio call initiation
- CallRecord creation
- Pipeline state updates
"""

from celery import Task
from backend.app.celery_app import celery_app, get_worker_event_loop
from backend.app.domains.patient_feedback.twilio_integration import TwilioIntegration
from backend.app.services.call_service import CallService
from backend.app.services.openai_realtime_config_service import OpenAIRealtimeConfigService
from backend.app.models.call_record import CallOutcome
from backend.app.models.campaign import Campaign
from backend.app.models.geography import Geography
from datetime import datetime
import logging

logger = logging.getLogger(__name__)


def get_or_create_event_loop():
    """Get existing event loop or create a new one if needed."""
    try:
        loop = asyncio.get_running_loop()
        return loop
    except RuntimeError:
        try:
            loop = asyncio.get_event_loop()
            if loop.is_closed():
                loop = asyncio.new_event_loop()
                asyncio.set_event_loop(loop)
            return loop
        except RuntimeError:
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            return loop


class VoiceCallTask(Task):
    """Base task for voice call operations with retry logic"""
    
    autoretry_for = (Exception,)
    retry_backoff = True
    retry_backoff_max = 600  # 10 minutes
    retry_jitter = True
    max_retries = 3


@celery_app.task(base=VoiceCallTask, bind=True, name="initiate_patient_call")
def initiate_patient_call(
    self,
    campaign_id: str,
    patient_phone: str,
    language: str = "en",
    status_callback_url: str = None
):
    """
    Initiate outbound call to patient.

    This task:
    1. Fetches campaign and geography
    2. Creates CallRecord in database
    3. Pre-warms OpenAI Realtime API connection (if enabled)
    4. Initiates Twilio outbound call
    5. Call connects to WebSocket endpoint for voice pipeline
    6. Updates CallRecord with Twilio metadata

    Args:
        campaign_id: Campaign ID
        patient_phone: Patient phone number (E.164 format)
        language: Language preference (en, es, fr, ht)
        status_callback_url: URL for Twilio status callbacks

    Returns:
        Dict with call_record_id and call_sid
    """
    logger.info(f"Initiating call to {patient_phone} for campaign {campaign_id}")

    try:
        loop = get_worker_event_loop()

        # 1. Fetch campaign and geography
        campaign = loop.run_until_complete(Campaign.get(campaign_id))
        if not campaign:
            raise ValueError(f"Campaign {campaign_id} not found")

        geography = None
        if campaign.geography_id:
            geography = loop.run_until_complete(Geography.get(campaign.geography_id))

        # 2. Create CallRecord
        call_record = loop.run_until_complete(CallService.create_call_record(
            campaign_id=campaign_id,
            patient_phone=patient_phone,
            language=language
        ))

        # 3. Pre-warm OpenAI Realtime API connection if enabled
        prewarmer_enabled = loop.run_until_complete(
            OpenAIRealtimeConfigService.is_prewarmer_enabled(campaign, geography)
        )

        if prewarmer_enabled:
            # Get Realtime API prewarmer instance (imported from global state)
            from backend.app.main import realtime_prewarmer

            if realtime_prewarmer and realtime_prewarmer.enabled:
                voice = OpenAIRealtimeConfigService.get_voice(campaign, language)
                temperature = OpenAIRealtimeConfigService.get_temperature(campaign)

                # NOTE: We can't pass instructions/tools here because they're dynamically
                # generated by FlowManager. For MVP, just pre-warm basic Realtime session.
                success = loop.run_until_complete(
                    realtime_prewarmer.pre_acquire_connection(
                        call_sid=str(call_record.id),  # Use CallRecord ID as key
                        voice=voice,
                        instructions=f"You are a healthcare assistant conducting a patient feedback call in {language} language.",
                        tools=[],  # Basic tools, FlowManager will update
                        temperature=temperature
                    )
                )

                if success:
                    logger.info(f"Pre-warmed OpenAI Realtime API connection for call {call_record.id}")
                else:
                    logger.warning(f"Failed to pre-warm Realtime API connection for call {call_record.id}, will use fresh connection")

        # 4. Initialize Twilio integration
        twilio = TwilioIntegration()

        # 5. Initiate Twilio call
        # The call will connect to the WebSocket endpoint which runs the voice pipeline
        call_data = twilio.initiate_call(
            to_number=patient_phone,
            campaign_id=campaign_id,
            patient_phone=patient_phone,
            language=language,
            status_callback_url=status_callback_url
        )

        # 6. Update CallRecord with Twilio metadata
        call_record.call_tracking.call_sid = call_data["call_sid"]
        call_record.call_tracking.status = call_data["status"]
        call_record.call_tracking.created_at = datetime.utcnow()
        loop.run_until_complete(call_record.save())

        logger.info(f"Call initiated: {call_data['call_sid']} for record {call_record.id}")

        return {
            "call_record_id": str(call_record.id),
            "call_sid": call_data["call_sid"],
            "status": call_data["status"]
        }

    except Exception as e:
        logger.error(f"Failed to initiate call: {e}", exc_info=True)
        
        # Update call record with error
        if 'call_record' in locals():
            call_record.error_message = str(e)
            call_record.call_tracking.outcome = CallOutcome.FAILED
            loop = get_worker_event_loop()
            loop.run_until_complete(call_record.save())
        
        raise


@celery_app.task(name="update_call_from_webhook")
def update_call_from_webhook(call_sid: str, status: str, duration: int = None):
    """
    Update CallRecord from Twilio status webhook.

    Args:
        call_sid: Twilio Call SID
        status: Call status (initiated, ringing, answered, completed, etc.)
        duration: Call duration in seconds (for completed calls)

    Returns:
        Dict with call_record_id and updated status
    """
    logger.info(f"Updating call {call_sid} with status {status}")

    try:
        loop = get_worker_event_loop()
        
        # Find call record by Twilio SID
        call_record = loop.run_until_complete(CallService.get_call_by_twilio_sid(call_sid))
        
        if not call_record:
            logger.warning(f"Call record not found for Twilio SID: {call_sid}")
            return None

        # Update status
        call_record.call_tracking.status = status

        # Handle status-specific updates
        if status == "ringing":
            # Call is ringing
            pass
        elif status == "in-progress" or status == "answered":
            call_record.call_tracking.started_at = datetime.utcnow()
        elif status == "completed":
            call_record.call_tracking.ended_at = datetime.utcnow()
            if duration:
                call_record.call_tracking.duration_seconds = int(duration)
            # Don't override outcome if pipeline already set it
            if not call_record.call_tracking.outcome:
                call_record.call_tracking.outcome = CallOutcome.SUCCESS
        elif status in ["busy", "no-answer", "failed", "canceled"]:
            call_record.call_tracking.ended_at = datetime.utcnow()
            if status == "busy":
                call_record.call_tracking.outcome = CallOutcome.BUSY
            elif status == "no-answer":
                call_record.call_tracking.outcome = CallOutcome.NO_ANSWER
            else:
                call_record.call_tracking.outcome = CallOutcome.FAILED

        call_record.updated_at = datetime.utcnow()
        loop.run_until_complete(call_record.save())

        logger.info(f"Updated call record {call_record.id} with status {status}")

        return {
            "call_record_id": str(call_record.id),
            "status": status
        }

    except Exception as e:
        logger.error(f"Failed to update call from webhook: {e}", exc_info=True)
        raise
